#!/usr/bin/env python3
"""
AGTI daily-pull cron job.

Runs once a day. Does the bookkeeping that does NOT require LLM judgment:

  1. Try to fetch the AGTI Intelligence Report for today's UTC date. If not
     yet published, fall back to yesterday's. Save raw HTML to daily/raw/.
  2. For every position in scripts/positions.json with status in {open}:
     - Pull latest yfinance close price.
     - Compute return %.
     - Apply exit rules (time stop T+5 trading days, stop_pct, take_pct).
     - If a rule fires, mark the position closed.
  3. For every status=pending position: try to fill at today's open if a
     trading day has elapsed since the report date.
  4. Write a summary to cron-runs/<UTC-date>.summary with: report fetched
     yes/no, marks computed, exits triggered, fills triggered, errors.
  5. Append a one-line entry to daily/<UTC-date>.md (creating it if missing)
     pointing to the raw report URL with a "TODO: extract signals" placeholder.
     Signal extraction stays a human-in-loop step.

This script does NOT update tracker.md — the source of truth is positions.json
and the cron-runs summaries. tracker.md is regenerated by hand or by a
separate human-readable rendering pass.

Telegram notification: writes the summary to cron-runs/<date>.summary; a
separate bot can pick it up and notify. Direct Telegram send-from-cron is
out of scope here to avoid stuffing bot tokens into this script.
"""
from __future__ import annotations

import json
import sys
import urllib.request
import urllib.error
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
POSITIONS_PATH = ROOT / "scripts" / "positions.json"
DAILY_DIR = ROOT / "daily"
RAW_DIR = DAILY_DIR / "raw"
RUNS_DIR = ROOT / "cron-runs"
INDEX_URL = "https://agtico.github.io/intelligence-reports"

# US market trading-day approximation: Mon-Fri minus US federal holidays.
# Cron already runs daily so we just check weekday on date math; holidays
# create a small drift in the T+5 rule that is acceptable for a paper book.

def is_trading_day(d: datetime) -> bool:
    return d.weekday() < 5  # Mon..Fri

def add_trading_days(start: datetime, n: int) -> datetime:
    cur = start
    added = 0
    while added < n:
        cur += timedelta(days=1)
        if is_trading_day(cur):
            added += 1
    return cur

def last_trading_day_on_or_before(d: datetime) -> datetime:
    cur = d
    while not is_trading_day(cur):
        cur -= timedelta(days=1)
    return cur

def try_fetch_report(date_str: str, slugs_to_try: list[str]) -> tuple[str, str] | None:
    """Returns (url, raw_html) of the first slug that 200s, or None."""
    y, m, d = date_str.split("-")
    for slug in slugs_to_try:
        url = f"{INDEX_URL}/{y}/{m}/{d}/{slug}/"
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "agti-daily-pull/1.0"})
            with urllib.request.urlopen(req, timeout=15) as r:
                if r.status == 200:
                    return url, r.read().decode("utf-8", errors="replace")
        except (urllib.error.HTTPError, urllib.error.URLError):
            continue
    return None

def fetch_index_for_today_or_yesterday(today: datetime) -> tuple[str, str, datetime] | None:
    """Pull the index page and find the most recent report URL.

    Returns (url, raw_html, report_publication_date) for the newest report at
    or before `today`, else None.
    """
    try:
        req = urllib.request.Request(INDEX_URL, headers={"User-Agent": "agti-daily-pull/1.0"})
        with urllib.request.urlopen(req, timeout=15) as r:
            index_html = r.read().decode("utf-8", errors="replace")
    except (urllib.error.HTTPError, urllib.error.URLError) as e:
        return None

    # Look for the most recent /YYYY/MM/DD/slug/ at or before today.
    import re
    pattern = re.compile(r"/intelligence-reports/(\d{4})/(\d{2})/(\d{2})/([a-z0-9\-]+)/")
    candidates = []
    for match in pattern.finditer(index_html):
        y, m, d, slug = match.groups()
        rep_date = datetime(int(y), int(m), int(d), tzinfo=timezone.utc)
        if rep_date <= today:
            candidates.append((rep_date, slug))
    if not candidates:
        return None
    # Newest first
    candidates.sort(key=lambda x: x[0], reverse=True)
    rep_date, slug = candidates[0]
    url = f"{INDEX_URL}/{rep_date.strftime('%Y/%m/%d')}/{slug}/"
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "agti-daily-pull/1.0"})
        with urllib.request.urlopen(req, timeout=15) as r:
            raw = r.read().decode("utf-8", errors="replace")
        return url, raw, rep_date
    except (urllib.error.HTTPError, urllib.error.URLError):
        return None

def fetch_close(ticker: str) -> float | None:
    try:
        import yfinance as yf
    except ImportError:
        return None
    try:
        h = yf.Ticker(ticker).history(period="5d", interval="1d")
        if h.empty:
            return None
        return float(h["Close"].iloc[-1])
    except Exception:
        return None

def fetch_open(ticker: str, date: str) -> float | None:
    """Open price on a specific date (YYYY-MM-DD)."""
    try:
        import yfinance as yf
    except ImportError:
        return None
    try:
        target = datetime.strptime(date, "%Y-%m-%d")
        h = yf.Ticker(ticker).history(start=target.strftime("%Y-%m-%d"),
                                       end=(target + timedelta(days=1)).strftime("%Y-%m-%d"),
                                       interval="1d")
        if h.empty:
            return None
        return float(h["Open"].iloc[0])
    except Exception:
        return None

def compute_pct(direction: str, entry: float, mark: float) -> float:
    if direction == "long":
        return (mark - entry) / entry
    elif direction == "short":
        return (entry - mark) / entry
    raise ValueError(f"unknown direction: {direction}")

def main() -> int:
    now = datetime.now(timezone.utc)
    today_str = now.strftime("%Y-%m-%d")

    DAILY_DIR.mkdir(parents=True, exist_ok=True)
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    RUNS_DIR.mkdir(parents=True, exist_ok=True)

    summary = {
        "run_at": now.isoformat(),
        "today": today_str,
        "report_fetched": None,
        "report_url": None,
        "report_publication_date": None,
        "marks_computed": 0,
        "exits_triggered": [],
        "fills_triggered": [],
        "errors": [],
    }

    # 1. Fetch most recent report at or before today
    fetched = fetch_index_for_today_or_yesterday(now)
    if fetched is None:
        summary["report_fetched"] = False
        summary["errors"].append("could not fetch agtico index or any candidate report")
    else:
        url, raw, rep_date = fetched
        summary["report_fetched"] = True
        summary["report_url"] = url
        summary["report_publication_date"] = rep_date.strftime("%Y-%m-%d")

        # Save raw report content
        raw_path = RAW_DIR / f"{rep_date.strftime('%Y-%m-%d')}.html"
        raw_path.write_text(raw)

        # Append to daily/<rep_date>.md if not already covered
        daily_path = DAILY_DIR / f"{rep_date.strftime('%Y-%m-%d')}.md"
        if not daily_path.exists():
            daily_path.write_text(
                f"# AGTI Paper Trade Log -- {rep_date.strftime('%Y-%m-%d')}\n\n"
                f"## Source report\n"
                f"- **URL:** {url}\n"
                f"- **Fetched:** {now.isoformat()}\n"
                f"- **Raw saved:** `daily/raw/{rep_date.strftime('%Y-%m-%d')}.html`\n\n"
                f"## Signals extracted\n\n"
                f"**TODO: extract signals** -- this is a human-in-loop step. "
                f"Run signal-extraction against the saved raw, then update "
                f"`scripts/positions.json` with new entries. Mark this section "
                f"with the per-signal table once extraction is complete.\n"
            )

    # 2. Load positions, mark + exit + fill
    if not POSITIONS_PATH.exists():
        summary["errors"].append(f"positions file missing: {POSITIONS_PATH}")
    else:
        positions = json.loads(POSITIONS_PATH.read_text())
        changed = False

        for pos in positions["positions"]:
            ticker = pos["ticker"]
            status = pos.get("status")

            # Try fill on pending positions
            if status == "pending":
                rep_date_str = pos.get("report_date")
                if rep_date_str:
                    rep_date = datetime.strptime(rep_date_str, "%Y-%m-%d").replace(tzinfo=timezone.utc)
                    next_td = rep_date
                    while not is_trading_day(next_td) or next_td <= rep_date:
                        next_td += timedelta(days=1)
                        if is_trading_day(next_td) and next_td > rep_date:
                            break
                    if now.date() >= next_td.date():
                        fill_price = fetch_open(ticker, next_td.strftime("%Y-%m-%d"))
                        if fill_price is not None:
                            pos["entry_price"] = fill_price
                            pos["entry_date"] = next_td.strftime("%Y-%m-%d")
                            pos["status"] = "open"
                            summary["fills_triggered"].append({
                                "ticker": ticker, "fill_date": next_td.strftime("%Y-%m-%d"),
                                "fill_price": fill_price,
                            })
                            changed = True
                        else:
                            summary["errors"].append(f"could not fetch fill price for {ticker} on {next_td.strftime('%Y-%m-%d')}")

            # Mark + exit on open positions
            if pos.get("status") == "open":
                mark = fetch_close(ticker)
                if mark is None:
                    summary["errors"].append(f"could not fetch mark for {ticker}")
                    continue
                summary["marks_computed"] += 1

                pct = compute_pct(pos["direction"], pos["entry_price"], mark)
                pos["last_mark"] = mark
                pos["last_mark_pct"] = pct
                pos["last_mark_date"] = today_str
                changed = True

                # Time stop
                entry_date = datetime.strptime(pos["entry_date"], "%Y-%m-%d").replace(tzinfo=timezone.utc)
                horizon = pos.get("horizon", "T+5_default")
                if horizon == "T+5_default":
                    expiry = add_trading_days(entry_date, 5)
                    if now.date() >= expiry.date():
                        pos["status"] = "closed"
                        pos["exit_date"] = today_str
                        pos["exit_price"] = mark
                        pos["exit_pct"] = pct
                        pos["exit_reason"] = "time_stop_T+5"
                        summary["exits_triggered"].append({
                            "ticker": ticker, "reason": "time_stop_T+5",
                            "exit_price": mark, "exit_pct": pct,
                        })
                        continue

                # Catalyst stop
                if horizon.startswith("catalyst:"):
                    cat_date_str = horizon.split(":", 1)[1]
                    try:
                        cat_date = datetime.strptime(cat_date_str, "%Y-%m-%d").replace(tzinfo=timezone.utc)
                        if now.date() >= cat_date.date():
                            pos["status"] = "closed"
                            pos["exit_date"] = today_str
                            pos["exit_price"] = mark
                            pos["exit_pct"] = pct
                            pos["exit_reason"] = f"catalyst_expiry_{cat_date_str}"
                            summary["exits_triggered"].append({
                                "ticker": ticker, "reason": f"catalyst_expiry_{cat_date_str}",
                                "exit_price": mark, "exit_pct": pct,
                            })
                            continue
                    except ValueError:
                        summary["errors"].append(f"bad catalyst date for {ticker}: {cat_date_str}")

                # Stop loss
                stop_pct = pos.get("stop_pct", -0.15)
                if pct <= stop_pct:
                    pos["status"] = "closed"
                    pos["exit_date"] = today_str
                    pos["exit_price"] = mark
                    pos["exit_pct"] = pct
                    pos["exit_reason"] = f"stop_loss_{stop_pct:+.0%}"
                    summary["exits_triggered"].append({
                        "ticker": ticker, "reason": f"stop_loss_{stop_pct:+.0%}",
                        "exit_price": mark, "exit_pct": pct,
                    })
                    continue

                # Take profit
                take_pct = pos.get("take_pct", 0.30)
                if pct >= take_pct:
                    pos["status"] = "closed"
                    pos["exit_date"] = today_str
                    pos["exit_price"] = mark
                    pos["exit_pct"] = pct
                    pos["exit_reason"] = f"take_profit_{take_pct:+.0%}"
                    summary["exits_triggered"].append({
                        "ticker": ticker, "reason": f"take_profit_{take_pct:+.0%}",
                        "exit_price": mark, "exit_pct": pct,
                    })
                    continue

        if changed:
            POSITIONS_PATH.write_text(json.dumps(positions, indent=2, sort_keys=True) + "\n")

    # 3. Write summary
    summary_path = RUNS_DIR / f"{today_str}.summary.json"
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")

    # Also write a human-readable summary
    text_path = RUNS_DIR / f"{today_str}.summary.txt"
    lines = [
        f"AGTI daily-pull cron run -- {now.isoformat()}",
        f"  report_fetched: {summary['report_fetched']}",
        f"  report_url: {summary['report_url']}",
        f"  report_pub_date: {summary['report_publication_date']}",
        f"  marks_computed: {summary['marks_computed']}",
        f"  fills_triggered: {len(summary['fills_triggered'])}",
        f"  exits_triggered: {len(summary['exits_triggered'])}",
        f"  errors: {len(summary['errors'])}",
    ]
    for f in summary["fills_triggered"]:
        lines.append(f"  FILL: {f['ticker']} @ {f['fill_price']} on {f['fill_date']}")
    for e in summary["exits_triggered"]:
        lines.append(f"  EXIT: {e['ticker']} ({e['reason']}) @ {e['exit_price']} ({e['exit_pct']:+.2%})")
    for err in summary["errors"]:
        lines.append(f"  ERR: {err}")
    text_path.write_text("\n".join(lines) + "\n")

    print(text_path.read_text())
    return 0 if not summary["errors"] else 0  # don't block cron on yfinance hiccups

if __name__ == "__main__":
    sys.exit(main())
